development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  port: 3306
  username: root
  password: password5
  database: articles_development

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  port: 3306
  username: root
  password: password5
  database: articles_test
